FROM openjdk:8
EXPOSE 9090
ARG JAR_FILE=target/docker-jenkins-integration-sample.jar
ADD ${JAR_FILE} docker-jenkins-integration-sample.jar
ENTRYPOINT ["java","-jar","/docker-jenkins-integration-sample.jar"]